name: <%= _.slugify(appname) %>
markdown: redcarpet
pygments: true
exclude: ['scss']
author_name: <%= authorName %>
author_github: <%= authorGithub %>
author_twitter: <%= authorTwitter %>
author_email: <%= authorEmail %>
