name: <%= _.slugify(appname) %>
markdown: redcarpet
pygments: true
exclude: ['scss']
author_name: <%= authorName %>
author_email: <%= authorEmail %>
username_github: <%= usernameGithub %>
username_twitter: <%= usernameTwitter %>
url_github: https://github.com/<%= usernameGithub %>
url_twitter: https://twitter.com/<%= usernameTwitter %>
